[project]
name = "djangotube"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.2",
    "imagekitio>=5.2.0",
    "pillow>=12.1.1",
    "python-dotenv>=1.2.1",
]
